FONT_FILE   = "geom.txt"      # your base-64 payload (one line, no quotes)
BYTES_PER_CHUNK = 1000        # keep well under 24 kB-per-literal limit

# ----------------------------------------------------------------------
b64 = open(FONT_FILE, "rt").read().strip()
chunks = [b64[i:i+BYTES_PER_CHUNK] for i in range(0, len(b64), BYTES_PER_CHUNK)]

print("// Auto-generated by split_font.py")
print("library FontStore {")
for i, c in enumerate(chunks):
    print(f'    string internal constant SLICE_{i} = "{c}";')
print("\n    function fontBase64() internal pure returns (string memory) {")
print("        return string(abi.encodePacked(")
print("            ", ",\n            ".join([f"SLICE_{i}" for i in range(len(chunks))]))
print("        ));")
print("    }")
print("}")